name 'django'
maintainer 'Manuel Ignacio Franco'
maintainer_email 'maigfrga@gmail.com'
license 'Apache 2.0'
description 'Installs/Configure a django instance over a debian box'
version '0.1.0'

depends 'postgresql'
depends 'python'
depends 'supervisor'
